

export const REGISTER_REQUEST ="REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"




export const LOGIN_REQUEST ="LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCESS"
export const LOGIN_FAILURE = "LOGINt_FAILURE"