export const JOB_DETAILS_GET_REQ = "JOB_DETAILS_GET_REQ";
export const JOB_DETAILS_GET_SUCC = "JOB_DETAILS_GET_SUCC";
export const JOB_DETAILS_GET_FAIL = "JOB_DETAILS_GET_FAIL";


export const HOME_JOB_DETAILS_GET_REQ = "HOME_JOB_DETAILS_GET_REQ";
export const HOME_JOB_DETAILS_GET_SUCC = "HOME_JOB_DETAILS_GET_SUCC";
export const HOME_JOB_DETAILS_GET_FAIL = "HOME_JOB_DETAILS_GET_FAIL";